version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: mcdmapp
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    restart: always
    ports:
      - "8000:8000"
    environment:
      DB_USER: root
      DB_PASS: 12345678
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: mcdmapp
      SECRET_KEY: your_secret_key_here
    depends_on:
      - db
    volumes:
      - .:/app

volumes:
  db_data:
