version: "3.9"

services:
  web:
    build: .
    container_name: fahp_web
    ports:
      - "8000:8000"
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - SECRET_KEY=${SECRET_KEY}
    volumes:
      - .:/app
    command: python -u dmapp.py
    restart: always